### PR TITLE
Fix severity when report contains no vulnerabilities

### LINKED ISSUE #91: get_artifact_vulnerability_reports() Raises a Validation Error when report  has no vulnerabilites
Steps to reproduce
1. Have an artifact that has no vulnerabilities but has a report.
2. run a get_artifact_vulnerability_reports() method
3. You will get 
`*** pydantic_core._pydantic_core.ValidationError: 1 validation error for HarborVulnerabilityReport
severity
  Input should be 'Unknown', 'Negligible', 'Low', 'Medium', 'High', 'Critical' or 'None' [type=enum, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/enum`

IMHO you should get a report object with a `None` severity and empty `vulnerabilities` list

### PR DESCRIPTION
**Pull request by pkalemba**
fixes: https://github.com/unioslo/harborapi/issues/91

### CODE REVIEW

**Comment by pkalemba** [comment]
@pederhan can you look ? After upgrade to newest harbor this issue is a blocker for me

**Comment by pkalemba** [comment]
Bumping to 0.25.2 does not help

**Comment by pederhan** [comment]
Sorry for the delay. I will take a look ASAP.

**Review by pederhan — CHANGES_REQUESTED** [review]
The validator needs to be added to the code generation "fragment" for HarborVulnerabilityReport: https://github.com/unioslo/harborapi/blob/main/codegen/ast/fragments/scanner/harborvulnerabilityreport.py

I don't have permission to edit this PR's branch, so I have made a PR to yours here: https://github.com/pkalemba/harborapi/pull/1

**Review by pederhan — APPROVED** [review]
LGTM. Thanks for your contribution and sorry again for the delay.

**Comment by pkalemba** [comment]
No problem , i assume this is normal during summer on university :)

**Pull request merged**
